# Alembic 스크립트 템플릿
"""add_indexes_and_constraints

Revision ID: 173b7c98740b
Revises: e026b63af756
Create Date: 2025-12-26 18:46:59.133482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173b7c98740b'
down_revision = 'e026b63af756'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_lecture_block_unique_room_slot', 'lecture_blocks', ['day', 'period', 'room_id'], unique=True, postgresql_where=sa.text('room_id IS NOT NULL'))
    op.create_unique_constraint('uq_teacher_time_off_slot', 'teacher_time_offs', ['teacher_id', 'day', 'period'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_teacher_time_off_slot', 'teacher_time_offs', type_='unique')
    op.drop_index('ix_lecture_block_unique_room_slot', table_name='lecture_blocks', postgresql_where=sa.text('room_id IS NOT NULL'))
    # ### end Alembic commands ###
