# Alembic 스크립트 템플릿
"""Add name and owner_id to teachers

Revision ID: 46c7290b3fb6
Revises: 739d80b24ddd
Create Date: 2025-12-26 16:27:54.713107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c7290b3fb6'
down_revision = '739d80b24ddd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('teachers', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teachers', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'owner_id')
    op.drop_column('teachers', 'name')
    # ### end Alembic commands ###
