# Alembic 스크립트 템플릿
"""Add user isolation and wizard tables

Revision ID: 739d80b24ddd
Revises: 09ce3b7adc54
Create Date: 2025-12-26 16:18:22.011607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '739d80b24ddd'
down_revision = '09ce3b7adc54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_group_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('days', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('periods', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('classroom', sa.String(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_id'), 'schedule', ['id'], unique=False)
    op.create_table('school_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('total_grades', sa.Integer(), nullable=True),
    sa.Column('periods_per_day', sa.Integer(), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=True),
    sa.Column('lunch_period', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('teacher_time_offs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('attendance', 'student_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='학생 ID (students 테이블 참조)',
               existing_nullable=False)
    op.alter_column('attendance', 'teacher_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='교사 ID (users 테이블 참조)',
               existing_nullable=False)
    op.alter_column('attendance', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='출석 날짜',
               existing_nullable=False)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='출석 상태 (present, absent, late, early_leave, early_leave_request, completed, excused)',
               existing_nullable=False,
               existing_server_default=sa.text("'absent'::character varying"))
    op.alter_column('attendance', 'note',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('attendance', 'check_in_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='입실 시간',
               existing_nullable=True)
    op.alter_column('attendance', 'check_out_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='퇴실 시간',
               existing_nullable=True)
    op.alter_column('attendance', 'room_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='정독실/야자 공간 ID',
               existing_nullable=True)
    op.alter_column('attendance', 'scanned_token',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='스캔 시 사용된 동적 토큰',
               existing_nullable=True)
    op.alter_column('attendance', 'geo_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='GPS 및 Wi-Fi 원본 데이터 (JSON)',
               existing_nullable=True)
    op.alter_column('attendance', 'device_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='스캔 시 사용된 기기 ID',
               existing_nullable=True)
    op.alter_column('attendance', 'is_fraud_detected',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='부정행위 의심 기록 여부',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_attendance_date'), table_name='attendance')
    op.drop_index(op.f('idx_attendance_date_teacher'), table_name='attendance')
    op.drop_index(op.f('idx_attendance_device_id'), table_name='attendance')
    op.drop_index(op.f('idx_attendance_room_id'), table_name='attendance')
    op.drop_index(op.f('idx_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('idx_attendance_teacher_id'), table_name='attendance')
    op.create_index(op.f('ix_attendance_device_id'), 'attendance', ['device_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_room_id'), 'attendance', ['room_id'], unique=False)
    op.drop_constraint(op.f('attendance_student_id_fkey'), 'attendance', type_='foreignkey')
    op.drop_constraint(op.f('attendance_teacher_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'attendance', 'students', ['student_id'], ['id'])
    op.drop_table_comment(
        'attendance',
        existing_comment='출석 기록 테이블',
        schema=None
    )
    op.add_column('departments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_foreign_key(None, 'departments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('facilities', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_foreign_key(None, 'facilities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('lecture_blocks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('idx_blocks_time'), table_name='lecture_blocks')
    op.drop_constraint(op.f('uq_block_group_time'), 'lecture_blocks', type_='unique')
    op.create_index(op.f('ix_lecture_blocks_id'), 'lecture_blocks', ['id'], unique=False)
    op.create_foreign_key(None, 'lecture_blocks', 'facilities', ['room_id'], ['id'])
    op.add_column('lecture_groups', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('lecture_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_lecture_groups_schedule'), table_name='lecture_groups')
    op.create_index(op.f('ix_lecture_groups_id'), 'lecture_groups', ['id'], unique=False)
    op.create_foreign_key(None, 'lecture_groups', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'lecture_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lecture_groups', 'teachers', ['teacher_id'], ['id'])
    op.alter_column('location_settings', 'room_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='정독실/야자 공간 고유 ID (R01, R02, Y31 등)',
               existing_nullable=False)
    op.alter_column('location_settings', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               comment=None,
               existing_comment='Geo-Fence 중심 위도',
               existing_nullable=False)
    op.alter_column('location_settings', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               comment=None,
               existing_comment='Geo-Fence 중심 경도',
               existing_nullable=False)
    op.alter_column('location_settings', 'radius_m',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='허용 반경 (미터)',
               existing_nullable=False)
    op.alter_column('location_settings', 'allowed_wifi_bssid',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='허용된 Wi-Fi AP의 BSSID 목록 (JSON 배열)',
               existing_nullable=True)
    op.alter_column('location_settings', 'attendance_start_time',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='출석 가능 시작 시간 (HH:MM 형식)',
               existing_nullable=True)
    op.alter_column('location_settings', 'attendance_end_time',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='출석 가능 종료 시간 (HH:MM 형식)',
               existing_nullable=True)
    op.alter_column('location_settings', 'late_threshold_time',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='지각 기준 시간 (HH:MM 형식)',
               existing_nullable=True)
    op.alter_column('location_settings', 'checkout_time',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='야자 종료 시간 (HH:MM 형식)',
               existing_nullable=True)
    op.drop_index(op.f('idx_location_settings_room_id'), table_name='location_settings')
    op.create_index(op.f('ix_location_settings_room_id'), 'location_settings', ['room_id'], unique=False)
    op.drop_table_comment(
        'location_settings',
        existing_comment='정독실 및 야자 공간 위치 설정 테이블',
        schema=None
    )
    op.alter_column('schedule_metadata', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_schedule_metadata_active'), table_name='schedule_metadata')
    op.create_index(op.f('ix_schedule_metadata_id'), 'schedule_metadata', ['id'], unique=False)
    op.drop_column('schedule_metadata', 'semester')
    op.drop_column('schedule_metadata', 'name')
    op.add_column('school_classes', sa.Column('class_number', sa.Integer(), nullable=True))
    op.add_column('school_classes', sa.Column('homeroom_teacher_id', sa.Integer(), nullable=True))
    op.alter_column('school_classes', 'grade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school_classes', 'class_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('school_classes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_school_classes_grade'), table_name='school_classes')
    op.drop_index(op.f('idx_school_classes_school'), table_name='school_classes')
    op.drop_constraint(op.f('school_classes_school_id_grade_class_name_academic_year_sem_key'), 'school_classes', type_='unique')
    op.create_index(op.f('ix_school_classes_id'), 'school_classes', ['id'], unique=False)
    op.create_foreign_key(None, 'school_classes', 'teachers', ['homeroom_teacher_id'], ['id'])
    op.drop_table_comment(
        'school_classes',
        existing_comment='학교 반 정보 (1학년 1반, 2학년 3반 등)',
        schema=None
    )
    op.drop_column('school_classes', 'semester')
    op.drop_column('school_classes', 'academic_year')
    op.drop_column('school_classes', 'school_id')
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('students', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_students_grade_class'), table_name='students')
    op.drop_index(op.f('idx_students_school_id'), table_name='students')
    op.drop_index(op.f('idx_students_user_id'), table_name='students')
    op.drop_constraint(op.f('students_student_number_key'), 'students', type_='unique')
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.drop_constraint(op.f('students_user_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    op.add_column('subjects', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE subjects SET name = 'Unknown Subject' WHERE name IS NULL")
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('subjects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('subjects_name_dept_unique'), 'subjects', type_='unique')
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_foreign_key(None, 'subjects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subjects', 'subject_type')
    op.drop_column('subjects', 'updated_at')
    op.drop_column('subjects', 'department_name')
    op.drop_column('subjects', 'credit_hours')
    op.drop_column('subjects', 'subject_name')
    op.add_column('teacher_constraints', sa.Column('reason', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('uq_teacher_constraint'), 'teacher_constraints', type_='unique')
    op.create_index(op.f('ix_teacher_constraints_id'), 'teacher_constraints', ['id'], unique=False)
    op.create_foreign_key(None, 'teacher_constraints', 'teachers', ['teacher_id'], ['id'])
    op.execute("ALTER TABLE teacher_timetables DROP CONSTRAINT IF EXISTS teacher_timetables_day_of_week_check")
    op.execute("ALTER TABLE teacher_timetables DROP CONSTRAINT IF EXISTS teacher_timetables_semester_check")
    op.execute("ALTER TABLE teacher_timetables DROP CONSTRAINT IF EXISTS teacher_timetables_period_check")
    op.drop_index(op.f('idx_teacher_timetables_day_period'), table_name='teacher_timetables')
    op.drop_index(op.f('idx_teacher_timetables_school'), table_name='teacher_timetables')
    op.drop_index(op.f('idx_teacher_timetables_teacher'), table_name='teacher_timetables')
    op.drop_constraint(op.f('teacher_timetables_teacher_id_day_of_week_period_academic_y_key'), 'teacher_timetables', type_='unique')
    op.drop_constraint(op.f('teacher_timetables_teacher_id_fkey'), 'teacher_timetables', type_='foreignkey')
    op.drop_constraint(op.f('teacher_timetables_class_id_fkey'), 'teacher_timetables', type_='foreignkey')
    op.add_column('teacher_timetables', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('teacher_timetables', sa.Column('grade', sa.Integer(), nullable=True))
    op.add_column('teacher_timetables', sa.Column('class_number', sa.Integer(), nullable=True))
    op.add_column('teacher_timetables', sa.Column('year', sa.Integer(), nullable=True))
    op.alter_column('teacher_timetables', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teacher_timetables', 'day_of_week',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True,
               comment=None,
               existing_comment='요일 (1=월, 2=화, 3=수, 4=목, 5=금)')
    op.alter_column('teacher_timetables', 'period',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='교시 (1-10)')
    op.alter_column('teacher_timetables', 'semester',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teacher_timetables', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_teacher_timetables_id'), 'teacher_timetables', ['id'], unique=False)
    op.create_foreign_key(None, 'teacher_timetables', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'teacher_timetables', 'subjects', ['subject_id'], ['id'])
    op.drop_table_comment(
        'teacher_timetables',
        existing_comment='교사 수업 시간표',
        schema=None
    )
    op.drop_column('teacher_timetables', 'updated_at')
    op.drop_column('teacher_timetables', 'school_id')
    op.drop_column('teacher_timetables', 'class_id')
    op.drop_column('teacher_timetables', 'subject_name')
    op.drop_column('teacher_timetables', 'academic_year')
    op.alter_column('teachers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('teachers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_teachers_school_id'), table_name='teachers')
    op.drop_constraint(op.f('teachers_teacher_number_key'), 'teachers', type_='unique')
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_nickname'), table_name='users')
    op.drop_index(op.f('idx_users_user_type'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_nickname_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_nickname_key'), 'users', ['nickname'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_index(op.f('idx_users_nickname'), 'users', ['nickname'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.create_unique_constraint(op.f('teachers_teacher_number_key'), 'teachers', ['teacher_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.alter_column('teachers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('teachers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('teacher_timetables', sa.Column('academic_year', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.add_column('teacher_timetables', sa.Column('subject_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('teacher_timetables', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('teacher_timetables', sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('teacher_timetables', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'teacher_timetables',
        '교사 수업 시간표',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'teacher_timetables', type_='foreignkey')
    op.drop_constraint(None, 'teacher_timetables', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_timetables_class_id_fkey'), 'teacher_timetables', 'school_classes', ['class_id'], ['id'])
    op.create_foreign_key(op.f('teacher_timetables_teacher_id_fkey'), 'teacher_timetables', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_teacher_timetables_id'), table_name='teacher_timetables')
    op.create_unique_constraint(op.f('teacher_timetables_teacher_id_day_of_week_period_academic_y_key'), 'teacher_timetables', ['teacher_id', 'day_of_week', 'period', 'academic_year', 'semester'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_teacher_timetables_teacher'), 'teacher_timetables', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_teacher_timetables_school'), 'teacher_timetables', ['school_id'], unique=False)
    op.create_index(op.f('idx_teacher_timetables_day_period'), 'teacher_timetables', ['day_of_week', 'period'], unique=False)
    op.alter_column('teacher_timetables', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('teacher_timetables', 'semester',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teacher_timetables', 'period',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='교시 (1-10)')
    op.alter_column('teacher_timetables', 'day_of_week',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False,
               comment='요일 (1=월, 2=화, 3=수, 4=목, 5=금)')
    op.alter_column('teacher_timetables', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('teacher_timetables', 'year')
    op.drop_column('teacher_timetables', 'class_number')
    op.drop_column('teacher_timetables', 'grade')
    op.drop_column('teacher_timetables', 'subject_id')
    op.drop_constraint(None, 'teacher_constraints', type_='foreignkey')
    op.drop_index(op.f('ix_teacher_constraints_id'), table_name='teacher_constraints')
    op.create_unique_constraint(op.f('uq_teacher_constraint'), 'teacher_constraints', ['schedule_id', 'teacher_id', 'day', 'period'], postgresql_nulls_not_distinct=False)
    op.drop_column('teacher_constraints', 'reason')
    op.add_column('subjects', sa.Column('subject_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('subjects', sa.Column('credit_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subjects', sa.Column('department_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('subjects', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('subjects', sa.Column('subject_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.create_unique_constraint(op.f('subjects_name_dept_unique'), 'subjects', ['subject_name', 'department_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('subjects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('subjects', 'user_id')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_user_id_fkey'), 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.create_unique_constraint(op.f('students_student_number_key'), 'students', ['student_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_students_user_id'), 'students', ['user_id'], unique=False)
    op.create_index(op.f('idx_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_index(op.f('idx_students_grade_class'), 'students', ['grade', 'class_number'], unique=False)
    op.alter_column('students', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('students', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('school_classes', sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school_classes', sa.Column('academic_year', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.add_column('school_classes', sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table_comment(
        'school_classes',
        '학교 반 정보 (1학년 1반, 2학년 3반 등)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'school_classes', type_='foreignkey')
    op.drop_index(op.f('ix_school_classes_id'), table_name='school_classes')
    op.create_unique_constraint(op.f('school_classes_school_id_grade_class_name_academic_year_sem_key'), 'school_classes', ['school_id', 'grade', 'class_name', 'academic_year', 'semester'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_school_classes_school'), 'school_classes', ['school_id'], unique=False)
    op.create_index(op.f('idx_school_classes_grade'), 'school_classes', ['grade'], unique=False)
    op.alter_column('school_classes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('school_classes', 'class_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('school_classes', 'grade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('school_classes', 'homeroom_teacher_id')
    op.drop_column('school_classes', 'class_number')
    op.add_column('schedule_metadata', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('schedule_metadata', sa.Column('semester', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_schedule_metadata_id'), table_name='schedule_metadata')
    op.create_index(op.f('idx_schedule_metadata_active'), 'schedule_metadata', ['is_active'], unique=False)
    op.alter_column('schedule_metadata', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'location_settings',
        '정독실 및 야자 공간 위치 설정 테이블',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_location_settings_room_id'), table_name='location_settings')
    op.create_index(op.f('idx_location_settings_room_id'), 'location_settings', ['room_id'], unique=False)
    op.alter_column('location_settings', 'checkout_time',
               existing_type=sa.VARCHAR(length=10),
               comment='야자 종료 시간 (HH:MM 형식)',
               existing_nullable=True)
    op.alter_column('location_settings', 'late_threshold_time',
               existing_type=sa.VARCHAR(length=10),
               comment='지각 기준 시간 (HH:MM 형식)',
               existing_nullable=True)
    op.alter_column('location_settings', 'attendance_end_time',
               existing_type=sa.VARCHAR(length=10),
               comment='출석 가능 종료 시간 (HH:MM 형식)',
               existing_nullable=True)
    op.alter_column('location_settings', 'attendance_start_time',
               existing_type=sa.VARCHAR(length=10),
               comment='출석 가능 시작 시간 (HH:MM 형식)',
               existing_nullable=True)
    op.alter_column('location_settings', 'allowed_wifi_bssid',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='허용된 Wi-Fi AP의 BSSID 목록 (JSON 배열)',
               existing_nullable=True)
    op.alter_column('location_settings', 'radius_m',
               existing_type=sa.INTEGER(),
               comment='허용 반경 (미터)',
               existing_nullable=False)
    op.alter_column('location_settings', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               comment='Geo-Fence 중심 경도',
               existing_nullable=False)
    op.alter_column('location_settings', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               comment='Geo-Fence 중심 위도',
               existing_nullable=False)
    op.alter_column('location_settings', 'room_id',
               existing_type=sa.VARCHAR(length=50),
               comment='정독실/야자 공간 고유 ID (R01, R02, Y31 등)',
               existing_nullable=False)
    op.drop_constraint(None, 'lecture_groups', type_='foreignkey')
    op.drop_constraint(None, 'lecture_groups', type_='foreignkey')
    op.drop_constraint(None, 'lecture_groups', type_='foreignkey')
    op.drop_index(op.f('ix_lecture_groups_id'), table_name='lecture_groups')
    op.create_index(op.f('idx_lecture_groups_schedule'), 'lecture_groups', ['schedule_id'], unique=False)
    op.alter_column('lecture_groups', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('lecture_groups', 'user_id')
    op.drop_constraint(None, 'lecture_blocks', type_='foreignkey')
    op.drop_index(op.f('ix_lecture_blocks_id'), table_name='lecture_blocks')
    op.create_unique_constraint(op.f('uq_block_group_time'), 'lecture_blocks', ['group_id', 'day', 'period'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_blocks_time'), 'lecture_blocks', ['day', 'period'], unique=False)
    op.drop_column('lecture_blocks', 'created_at')
    op.drop_constraint(None, 'facilities', type_='foreignkey')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_column('facilities', 'user_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_column('departments', 'user_id')
    op.create_table_comment(
        'attendance',
        '출석 기록 테이블',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_teacher_id_fkey'), 'attendance', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('attendance_student_id_fkey'), 'attendance', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_attendance_room_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_device_id'), table_name='attendance')
    op.create_index(op.f('idx_attendance_teacher_id'), 'attendance', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_index(op.f('idx_attendance_room_id'), 'attendance', ['room_id'], unique=False)
    op.create_index(op.f('idx_attendance_device_id'), 'attendance', ['device_id'], unique=False)
    op.create_index(op.f('idx_attendance_date_teacher'), 'attendance', ['date', 'teacher_id'], unique=False)
    op.create_index(op.f('idx_attendance_date'), 'attendance', ['date'], unique=False)
    op.alter_column('attendance', 'is_fraud_detected',
               existing_type=sa.BOOLEAN(),
               comment='부정행위 의심 기록 여부',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('attendance', 'device_id',
               existing_type=sa.VARCHAR(length=255),
               comment='스캔 시 사용된 기기 ID',
               existing_nullable=True)
    op.alter_column('attendance', 'geo_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='GPS 및 Wi-Fi 원본 데이터 (JSON)',
               existing_nullable=True)
    op.alter_column('attendance', 'scanned_token',
               existing_type=sa.TEXT(),
               comment='스캔 시 사용된 동적 토큰',
               existing_nullable=True)
    op.alter_column('attendance', 'room_id',
               existing_type=sa.VARCHAR(length=50),
               comment='정독실/야자 공간 ID',
               existing_nullable=True)
    op.alter_column('attendance', 'check_out_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='퇴실 시간',
               existing_nullable=True)
    op.alter_column('attendance', 'check_in_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='입실 시간',
               existing_nullable=True)
    op.alter_column('attendance', 'note',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='출석 상태 (present, absent, late, early_leave, early_leave_request, completed, excused)',
               existing_nullable=False,
               existing_server_default=sa.text("'absent'::character varying"))
    op.alter_column('attendance', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='출석 날짜',
               existing_nullable=False)
    op.alter_column('attendance', 'teacher_id',
               existing_type=sa.INTEGER(),
               comment='교사 ID (users 테이블 참조)',
               existing_nullable=False)
    op.alter_column('attendance', 'student_id',
               existing_type=sa.INTEGER(),
               comment='학생 ID (students 테이블 참조)',
               existing_nullable=False)
    op.drop_table('teacher_time_offs')
    op.drop_table('school_configurations')
    op.drop_index(op.f('ix_schedule_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_table('block_group_definitions')
    # ### end Alembic commands ###
